Changes made for feedback pointers
Gemini-Solutions/QE-Hartron pull request #2
Opened 2024-04-10 13:36 UTC by gem-yudhisthir

I have pushed the UI Automation code for the following screens:

1)Candidate Test: 13 Test cases
2)User Management: 15 Test cases

To ensure the codebase is optimized and adheres to best practices, I have made several enhancements based on the feedback pointers.

2024-04-11 05:13 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/locators/CandidateTestLocators.java
> +    public static By evaluationStatusDropdown = By.xpath("//div[@class='ng-tns-c116-23 p-dropdown p-component p-dropdown-clearable']");
Fix this. Make it dynamic by using contains. These type of xpaths contains class that keep changing. Identify the part that do not change and include that part in the contains

2024-04-11 05:14 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/locators/CandidateTestLocators.java
> +    public static By detailedReport = By.xpath("//*[text()='Detailed Report']");
Do not use * for tagName. Specify it.

2024-04-11 05:15 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/locators/UserLocators.java
> +    public static By searchEmployeeBox = By.xpath("//p-tabpanel[@header='Employees']//input[@placeholder=\"First Name/Email\"]");
Use single code inside the xpaths to make it readable. Not a rulebook but a good practice to follow.

2024-04-11 05:16 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +            if (Search) {
Why variable name starts with capital letter? Follow appropriate naming convention to name literals in java.

2024-04-11 05:17 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +    @And("^Select (.+) from Skilll center dropdown$")
start the sentence inside ("^....$") with small letter as discussed in the last Peer review call. Ex: @And("^select (.+) from Skilll center dropdown$")

2024-04-11 05:18 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +                GemTestReporter.addTestStep("Select evaluation status from evaluator filter", "This step is executed successfully", STATUS.PASS);
Make the reporting part more readable

2024-04-11 05:19 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +                DriverAction.waitSec(5);
Please check if wait can be made dynamic here.

2024-04-11 05:21 UTC, gem-akatiha commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +    public void statusDropdownIsPresent() {
This method is same as the method at line 319. Make them generic to avoid redundancy.

2024-04-11 05:25 UTC, gem-akatiha requested changes
Please fix the issues mentioned in the comments and raise the PR again

2024-04-12 04:52 UTC, gem-yudhisthir commented on src/main/java/com/qa/gemini/stepdefinitions/CandidateTest.java
> +    @And("^Select (.+) from Skilll center dropdown$")
ok

2024-04-17 11:22 UTC, closed without merging

2024-04-17 11:22 UTC, gem-akatiha commented
Fix above changes and raise the PR again